# Configuration
# https://jekyllrb.com/docs/configuration/

# General
repository: FriendsOfREDAXO/tricks
timezone: Europe/Berlin
baseurl: /tricks

# Optional plugins
# https://help.github.com/articles/configuring-jekyll-plugins/#optional-plugins
plugins:
- jekyll-avatar
- jekyll-feed
- jekyll-mentions
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
- jemoji

# SEO
# https://github.com/jekyll/jekyll-seo-tag
title: REDAXO-Tricks
description: Nützliche Tricks für REDAXO 5
keywords: redaxo,community,cms,tricks,tutorial,docs,documentation,guide,doku,anleitung

# Assets
# https://jekyllrb.com/docs/assets/
sass:
  style: compressed

# Collections
# https://jekyllrb.com/docs/collections/
collections:
  docs:
    output: true
    permalink: /:path

# Defaults
# https://jekyllrb.com/docs/configuration/#front-matter-defaults
defaults:
  - scope:
      type: docs
    values:
      layout: docs

# Exclude directories and/or files from the conversion.
# https://jekyllrb.com/docs/configuration/
exclude:
- CONTRIBUTE.md
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- SETUP.md
- vendor
